name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # El pipeline se ejecuta automáticamente cuando haces push a la rama main
  pull_request:
    branches:
      - main  # También se ejecuta en pull requests a main
  workflow_dispatch:   # Permite ejecución manual del pipeline
    inputs:
      version:
        description: 'Versión para desplegar'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        
      - name: Instalar dependencias
        run: npm install  # Instala las dependencias de Node.js
      
      - name: Compilar el proyecto
        run: npm run build  # Si tienes un script de build, este lo ejecuta

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install  # Instala las dependencias antes de ejecutar pruebas

      - name: Ejecutar pruebas
        run: npm test  # Ejecuta las pruebas automatizadas

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'  # Solo ejecuta el despliegue si estamos en la rama main
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Desplegar en producción
        run: |
          echo "Desplegando la versión ${GITHUB_EVENT_INPUTS_VERSION} a producción..."
          # Aquí añades tus comandos de despliegue, por ejemplo:
          # npm run deploy  (o cualquier otro comando de despliegue que uses)
