# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-devops
  template:
    metadata:
      labels:
        app: microservicio-devops
    spec:
      containers:
      - name: microservicio-devops
        image: ${DOCKER_IMAGE}:${TAG}
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
        - name: NODE_ENV
          value: "production"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: microservicio-secrets
              key: jwt-secret